In [1]:
import pandas as pd
import numpy as np

In [2]:
DICT_WIKI_PATH = '/Users/harveymanhood/Documents/- datasets/words/dictionary_lowercase.txt'
DICT_WORD_PATH = '/Users/harveymanhood/Documents/- datasets/words/wikipedia_en.txt'

In [40]:
dict_wiki = pd.read_csv(DICT_WIKI_PATH,header=None,names=['word'])
dict_word = pd.read_csv(DICT_WORD_PATH,sep=' ',header=None,names=['word','len','instances','articles'])

In [41]:
dict_wiki['word'] = dict_wiki['word'].apply(lambda x: str(x).upper())
dict_wiki = dict_wiki.drop_duplicates()
dict_word['word'] = dict_word['word'].apply(lambda x: str(x).upper())
dict_word = dict_word.groupby(['word','len']).sum().sort_values(by='instances',ascending=False).reset_index()
dict_master = dict_word.merge(dict_wiki,how='inner',on='word',sort=False)

In [117]:
class Wordle:
    def __init__(self,data,n=5):
        self.data = data[data['len']==n].reset_index(drop=True)
        self.word = self.data['word'][np.random.randint(len(self.data))]
        
    def guess(self):
        t = 1
        match = np.zeros(len(self.word),dtype=int)
        while min(match) < 2:
            myguess = input('Guess '+str(t)+':')
            if len(myguess) != len(self.word):
                print('Please choose a '+str(len(self.word))+'-letter word!')
                continue
            else:
                for c in range(len(myguess)):
                    if myguess[c] == self.word[c]:
                        match[c] = 2
                    elif (myguess[c] in self.word) and (myguess[c] != self.word[c]):
                        match[c] = 1
                    else:
                        match[c] = 0
                if min(match) != 2:
                    t += 1
                    print(match)
        return 'you got it in '+str(t)+' tries :)'

In [118]:
word = Wordle(dict_master)

In [119]:
word.guess()

Guess 1: VOLES


[0 0 0 2 1]


Guess 2: STEAM


[1 1 1 0 0]


Guess 3: TIMES


[1 0 0 2 1]


Guess 4: ASSET


[0 2 1 2 1]


Guess 5: ESTER


'you got it in 5 tries :)'